sudo: required
dist: trusty
install: true

branches:
  only: 
    - master

language: java

notifications:
  email:
    recipients:
      - devcenter@docusign.com
    on_success: never
    on_failure: change

jdk:
  - oraclejdk9
  - oraclejdk11

script: mvn -X clean test

after_failure: "cat /home/travis/build/docusign/docusign-java-client/target/surefire-reports/SdkUnitTests.txt && cat /home/travis/build/docusign/docusign-java-client/target/surefire-reports/TEST-SdkUnitTests.xml"
